# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: products.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproducts.proto\"\x1d\n\x0fProductsRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"%\n\x08Products\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\"-\n\x10ProductsResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\";\n\x14ProductsResponseList\x12#\n\x08products\x18\x01 \x03(\x0b\x32\x11.ProductsResponse2E\n\x0fProductsService\x12\x32\n\x07Product\x12\x10.ProductsRequest\x1a\x15.ProductsResponseListb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'products_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCTSREQUEST._serialized_start=18
  _PRODUCTSREQUEST._serialized_end=47
  _PRODUCTS._serialized_start=49
  _PRODUCTS._serialized_end=86
  _PRODUCTSRESPONSE._serialized_start=88
  _PRODUCTSRESPONSE._serialized_end=133
  _PRODUCTSRESPONSELIST._serialized_start=135
  _PRODUCTSRESPONSELIST._serialized_end=194
  _PRODUCTSSERVICE._serialized_start=196
  _PRODUCTSSERVICE._serialized_end=265
# @@protoc_insertion_point(module_scope)
